name: Chromium i686 Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
      
      - name: Fetch Chromium Source
        run: |
          mkdir chromium && cd chromium
          fetch --nohooks chromium
          cd src
          git checkout main # Or a specific tag
          gclient sync
      
      - name: Install System Dependencies
        run: |
          cd chromium/src
          sudo ./build/install-build-deps.sh --lib32 --no-arm --no-nacl --no-prompt
      
      - name: Install i386 Sysroot
        run: |
          cd chromium/src
          python3 build/linux/sysroot_scripts/install-sysroot.py --arch=i386
          
      - name: GN Gen
        run: |
          cd chromium/src
          mkdir -p out/Release_x86
          gn gen out/Release_x86 --args='target_cpu="x86" is_debug=false symbol_level=0'
          
      - name: Build
        run: |
          cd chromium/src
          autoninja -C out/Release_x86 chrome
